name: Build and deploy PegasusHub Jekyll site to GitHub Pages

on:
  schedule:
    - cron: "0 */2 * * *"
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate workflows pages
        env:
          PEGASUSHUB_TOKEN: ${{ secrets.JEKYLL_PAT }}
        run: |
          python3 scripts/process.py
